// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: access_manager.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrantAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"` // "elk", "gitlab"
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAccessRequest) Reset() {
	*x = GrantAccessRequest{}
	mi := &file_access_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessRequest) ProtoMessage() {}

func (x *GrantAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantAccessRequest) Descriptor() ([]byte, []int) {
	return file_access_manager_proto_rawDescGZIP(), []int{0}
}

func (x *GrantAccessRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GrantAccessRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GrantAccessRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_access_manager_proto protoreflect.FileDescriptor

const file_access_manager_proto_rawDesc = "" +
	"\n" +
	"\x14access_manager.proto\x12\x04cscd\"`\n" +
	"\x12GrantAccessRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04roleB8Z6github.com/kortelyov/cscd/cscd-contracts/pkg/contractsb\x06proto3"

var (
	file_access_manager_proto_rawDescOnce sync.Once
	file_access_manager_proto_rawDescData []byte
)

func file_access_manager_proto_rawDescGZIP() []byte {
	file_access_manager_proto_rawDescOnce.Do(func() {
		file_access_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_access_manager_proto_rawDesc), len(file_access_manager_proto_rawDesc)))
	})
	return file_access_manager_proto_rawDescData
}

var file_access_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_access_manager_proto_goTypes = []any{
	(*GrantAccessRequest)(nil), // 0: cscd.GrantAccessRequest
}
var file_access_manager_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_access_manager_proto_init() }
func file_access_manager_proto_init() {
	if File_access_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_access_manager_proto_rawDesc), len(file_access_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_access_manager_proto_goTypes,
		DependencyIndexes: file_access_manager_proto_depIdxs,
		MessageInfos:      file_access_manager_proto_msgTypes,
	}.Build()
	File_access_manager_proto = out.File
	file_access_manager_proto_goTypes = nil
	file_access_manager_proto_depIdxs = nil
}
